#!/usr/bin/env docker.sh

image=wordpress:latest
must_local=y
net=net-$dirsum
opts="
  -p 8080:80
  -v '$dir/wp-root:/var/www/html'

  -e WORDPRESS_DB_HOST=db
  -e WORDPRESS_DB_PASSWORD=password

  --log-driver json-file
  --log-opt max-size=50m
  --log-opt max-file=3
"

pre_start() {
  "$dir/mariadb" start
}
