#!/usr/bin/env docker.sh

image=phpmyadmin/phpmyadmin:latest
net=net-$dirsum
opts="
  -p 8080:80

  -e PMA_HOST=db

  --log-driver json-file
  --log-opt max-size=50m
  --log-opt max-file=3
"

pre_start() {
  "$dir/mariadb" start
}
