#!/usr/bin/env docker.sh

image=thajeztah/pgadmin4
must_local=y
net=net0
opts_vol="-v '$dir/data:/pgadmin'"
opts="
  --restart always
  $opts_vol
  -p 5050:5050

  --log-driver json-file
  --log-opt max-size=50m
  --log-opt max-file=3
"

pre_start() {
  "$dir/../postgres/app" start || panic 'failed to start postgres'
  if [ "${1:-}" = run ]; then
    # we need to chown the dir, due to bind-mount will create directory owned by root.
    tmp=$(quote "$opts_vol") || panic
    eval "set -- $tmp"
    docker run -it --rm \
      "$@" \
      -u 0:0 --entrypoint /bin/sh \
      "$image" -c 'chown pgadmin:pgadmin /pgadmin'
  fi
}
