#!/usr/bin/env docker.sh

must_local=y
image=thajeztah/pgadmin4
net=net0
opts_vol="-v '$dir/data:/pgadmin'"
opts="
  --restart always
  $opts_vol
  -p 5050:5050
"

pre_start() {
  "$dir/../postgres/app" start || { echo 'failed to start postgres'; return 1; }
  if [ "${1:-}" = run ]; then
    # we need to chown the dir, due to bind-mount will create directory owned by root.
    tmp=$(quote "$opts_vol") || return 1
    eval "set -- $tmp"
    docker run -it --rm \
      "$@" \
      -u 0:0 --entrypoint /bin/sh \
      "$image" -c 'chown pgadmin:pgadmin /pgadmin'
  fi
}
